version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    image: sem-barreiras
    environment:
      - PORT=8080
      - APP_SECRET=test
      - STORAGE_DRIVER=disk
      - MONGO_URI=mongodb+srv://integradora2:integradora2@cluster0.p5gphdq.mongodb.net/test
      - APP_URI=https://sembarreiras.unze.com.br
    container_name: sem-barreiras-app
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: sem-barreiras-db
    image: mongo
    ports:
      - "27017:27017"
    logging:
      driver: none
